### ISSUE TITLE
Gun Missions

### ISSUE THREAD

**Issue by Ze0-Hossam** [cs304Project/Guns#2]
A description

## Todo
player's track?
- [ ] player movements, animation, collision detection
- [ ] player's projectile-like ( normal attack and special attack)
- [ ] player interactions like (health, power up)
- [ ] player's effect -> when it is dying

enemy's track?
- [ ] enemy movements, animation
- [ ] (Sample enemy AI) for example (advanced movements, automatically normal attack, automatically special attack)
- [ ] enemy's effect -> when it is dying
